#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct MemoryGateDecision {
    pub disposition: MemoryGateDisposition,
    pub route: &'static str,
    pub flags: Vec<&'static str>,
    pub reason: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum MemoryGateDisposition {
    Accept,
    ReviewOnly,
    Reject,
}

pub(crate) fn evaluate_memory_candidate(
    title: &str,
    body: &str,
    evidence: &str,
    kind: &str,
    scope: &str,
) -> MemoryGateDecision {
    let combined = format!("{title}\n{body}\n{evidence}\n{kind}\n{scope}");
    let lower = combined.to_lowercase();
    let durable = has_durable_marker(&lower);

    if contains_secret(&lower) {
        return reject("secret", "Candidate contains secret-like content.");
    }
    if looks_like_generated_or_internal_artifact(&lower) {
        return reject(
            "generated-or-internal-artifact",
            "Candidate is generated artifact or internal extraction metadata.",
        );
    }
    if looks_like_memory_pipeline_meta(&lower) {
        return reject(
            "memory-pipeline-meta",
            "Candidate describes the memory extraction pipeline, not durable user preference.",
        );
    }
    if looks_like_current_task_state(&lower) {
        return reject(
            "current-task-state",
            "Candidate describes current task state.",
        );
    }
    if looks_like_one_off_write_scope(&lower, durable) {
        return reject(
            "one-off-write-scope",
            "Candidate describes a one-off task write scope.",
        );
    }
    if looks_like_rebuildable_code_fact(&lower, durable) {
        return reject(
            "rebuildable-code-fact",
            "Candidate can be rediscovered from the current repository.",
        );
    }
    if looks_like_ephemeral_reference(&lower, durable) {
        return reject(
            "ephemeral-reference",
            "Candidate is likely to expire quickly.",
        );
    }
    if looks_like_reference_pointer(&lower) {
        return MemoryGateDecision {
            disposition: MemoryGateDisposition::ReviewOnly,
            route: "review_only",
            flags: vec!["reference-pointer"],
            reason: "Reference-like memories should be reviewed without default compilation.",
        };
    }
    MemoryGateDecision {
        disposition: MemoryGateDisposition::Accept,
        route: "always_on_rule",
        flags: Vec::new(),
        reason: "Candidate passed memory gate.",
    }
}

fn reject(flag: &'static str, reason: &'static str) -> MemoryGateDecision {
    MemoryGateDecision {
        disposition: MemoryGateDisposition::Reject,
        route: "review_only",
        flags: vec![flag],
        reason,
    }
}

fn has_durable_marker(lower: &str) -> bool {
    [
        "以后",
        "长期",
        "每次",
        "所有",
        "默认",
        "统一",
        "总是",
        "必须",
        "合规",
        "团队",
        "always",
        "by default",
        "for every",
        "for all",
        "must",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn contains_secret(lower: &str) -> bool {
    [
        "token=",
        "password=",
        "passwd=",
        "credential",
        "api_key",
        "apikey",
        "secret=",
        "密钥",
        "密码",
        "凭证",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_generated_or_internal_artifact(lower: &str) -> bool {
    [
        "generated by agent-kernel",
        "do not edit directly",
        "enabled memory_cards",
        "enabled skills",
        "contents of the agents.md",
        "contents of the claude.md",
        "observation synthesis",
        "source_observations",
        "matched_signal",
        "evidence:",
        "score:",
        "title:",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_current_task_state(lower: &str) -> bool {
    [
        "当前 pr",
        "current pr",
        "这个 pr",
        "本周 pr",
        "当前分支",
        "current branch",
        "正在改",
        "正在处理",
        "还有两项",
        "还有 2 项",
        "还有两个",
        "这次任务",
        "当前任务",
        "task status",
        "残留",
        "现有bug",
        "现有 bug",
        "重复这个问题",
        "分配页面",
        "调用claude code",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_memory_pipeline_meta(lower: &str) -> bool {
    if looks_like_durable_local_history_validation_workflow(lower) {
        return false;
    }
    if looks_like_supported_failure_flow_workflow(lower) {
        return false;
    }
    let candidate_pipeline_rule = lower.contains("候选记忆")
        || (lower.contains("候选质量") && lower.contains("候选数量"))
        || lower.contains("候选被判定为无长期价值")
        || lower.contains("真正值得固化的记忆")
        || (lower.contains("生成") && lower.contains("筛选") && lower.contains("候选"));
    let memory_pipeline_terms = lower.contains("提炼")
        || lower.contains("抽取")
        || lower.contains("筛选")
        || lower.contains("llm转写")
        || lower.contains("llm 转写");
    let generic_planning_principle = (lower.contains("当规划或评估开发工作时")
        || (lower.contains("核心功能链路") && lower.contains("周边功能")))
        && !lower.contains("所有项目")
        && !lower.contains("每次");
    let generation_quality_acceptance = looks_like_generation_quality_acceptance_chatter(lower);

    (candidate_pipeline_rule
        && (lower.contains("只保留")
            || lower.contains("高置信度")
            || lower.contains("可执行")
            || lower.contains("过滤")
            || lower.contains("质量优先")))
        || (memory_pipeline_terms && lower.contains("候选"))
        || generic_planning_principle
        || generation_quality_acceptance
}

fn looks_like_supported_failure_flow_workflow(lower: &str) -> bool {
    lower.contains("failureflowsummary:")
        && (lower.contains("signal:pipeline_break")
            || lower.contains("signal:final_quality_correction")
            || lower.contains("signal:false_positive_noise")
            || lower.contains("signal:privacy_boundary")
            || lower.contains("signal:scope_boundary")
            || lower.contains("signal:refactor_correction")
            || lower.contains("signal:transferable_workflow")
            || lower.contains("signal:review_iterate_loop"))
}

fn looks_like_durable_local_history_validation_workflow(lower: &str) -> bool {
    (lower.contains("真实历史") || lower.contains("real-history") || lower.contains("dry-run"))
        && (lower.contains("本地评估") || lower.contains("本地真实历史") || lower.contains("local"))
        && (lower.contains("不进入 git")
            || lower.contains("不要提交")
            || lower.contains("golden set")
            || lower.contains("只用于本地"))
        && (lower.contains("提炼质量") || lower.contains("抽取") || lower.contains("候选"))
}

fn looks_like_generation_quality_acceptance_chatter(lower: &str) -> bool {
    let generation_surface = [
        "prompt",
        "render",
        "rewrite",
        "llm",
        "模型",
        "卡片",
        "最终卡片",
        "成品卡片",
        "改写器",
        "memory card",
        "candidate",
        "候选",
        "生成",
        "提炼",
        "筛选",
    ]
    .iter()
    .filter(|marker| lower.contains(**marker))
    .count()
        >= 2;
    let eval_surface = [
        "抽样",
        "最终卡片",
        "分数",
        "指标",
        "人工看",
        "人工审阅",
        "质量",
        "评估",
        "golden",
        "eval",
        "score",
        "metric",
        "sample",
    ]
    .iter()
    .filter(|marker| lower.contains(**marker))
    .count()
        >= 2;
    let process_instruction = [
        "要",
        "不要",
        "不能只",
        "不应该只",
        "必须",
        "should",
        "must",
        "not only",
        "don't just",
    ]
    .iter()
    .any(|marker| lower.contains(marker));

    generation_surface && eval_surface && process_instruction
}

fn looks_like_one_off_write_scope(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    [
        "只修改",
        "仅修改",
        "只改 ",
        "不要改 rust",
        "不要动 rust",
        "不要改 src-tauri",
        "不要改前端",
        "不要改后端",
        "只读审查",
        "不要编辑文件",
        "不要修改文件",
        "modify only",
        "edit only",
        "do not touch rust",
        "do not modify",
        "read-only review",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_rebuildable_code_fact(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    let path_like = [
        ".rs",
        ".ts",
        ".tsx",
        ".js",
        ".py",
        "src/",
        "app/",
        "src-tauri/",
    ]
    .iter()
    .any(|marker| lower.contains(marker));
    path_like
        && [
            "这个函数",
            "函数现在在",
            "现在在",
            "located in",
            "lives in",
            "文件结构",
            "目录布局",
            "function signature",
        ]
        .iter()
        .any(|marker| lower.contains(marker))
}

fn looks_like_ephemeral_reference(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    [
        "pr #",
        "pull request #",
        "分支名",
        "branch name",
        "今天改了",
        "本周任务",
        "本周列表",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_reference_pointer(lower: &str) -> bool {
    lower.contains("http://")
        || lower.contains("https://")
        || lower.contains("看板")
        || lower.contains("dashboard")
        || lower.contains("监控")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decision(text: &str) -> MemoryGateDecision {
        evaluate_memory_candidate(text, text, text, "constraint", "project")
    }

    #[test]
    fn rejects_one_off_scope_without_durable_marker() {
        assert_eq!(
            decision("只修改 app/src/main.tsx，不要改 Rust。").disposition,
            MemoryGateDisposition::Reject
        );
        assert_eq!(
            decision("不要改 Rust。").disposition,
            MemoryGateDisposition::Reject
        );
    }

    #[test]
    fn keeps_durable_project_rule() {
        assert_eq!(
            decision("以后所有 Rust 项目提交前运行 cargo test。").disposition,
            MemoryGateDisposition::Accept
        );
    }

    #[test]
    fn rejects_memory_pipeline_meta_rules() {
        assert_eq!(
            decision("当生成、筛选或展示候选记忆时，只保留高置信度且可执行的少量候选。")
                .disposition,
            MemoryGateDisposition::Reject
        );
        assert_eq!(
            decision("当规划或评估开发工作时，先确保核心功能链路和用户体验稳定；再考虑周边功能。")
                .disposition,
            MemoryGateDisposition::Reject
        );
        assert_eq!(
            decision("修改卡片改写器时，必须抽样审阅最终卡片，不要只看质量分。").disposition,
            MemoryGateDisposition::Reject
        );
    }

    #[test]
    fn keeps_supported_failure_flow_workflow() {
        let decision = evaluate_memory_candidate(
            "提取异常先定位链路断点",
            "当记忆提取结果异常少、质量差或没有进入最终卡片阶段时，先定位链路断点，包括候选召回、LLM induction、JSON 解析、质量门控和 crystallize。",
            "FailureFlowSummary:\n- signal:pipeline_break obs:a text:LLM induction JSON 被截断，解析失败，所以没有进入最终 crystallize 卡片阶段。",
            "procedure",
            "global",
        );

        assert_eq!(decision.disposition, MemoryGateDisposition::Accept);
    }
}
