#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct MemoryGateDecision {
    pub disposition: MemoryGateDisposition,
    pub route: &'static str,
    pub flags: Vec<&'static str>,
    pub reason: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum MemoryGateDisposition {
    Accept,
    ReviewOnly,
    Reject,
}

pub(crate) fn evaluate_memory_candidate(
    title: &str,
    body: &str,
    evidence: &str,
    kind: &str,
    scope: &str,
) -> MemoryGateDecision {
    let combined = format!("{title}\n{body}\n{evidence}\n{kind}\n{scope}");
    let lower = combined.to_lowercase();
    let durable = has_durable_marker(&lower);

    if contains_secret(&lower) {
        return reject("secret", "Candidate contains secret-like content.");
    }
    if looks_like_generated_or_internal_artifact(&lower) {
        return reject(
            "generated-or-internal-artifact",
            "Candidate is generated artifact or internal extraction metadata.",
        );
    }
    if looks_like_current_task_state(&lower) {
        return reject(
            "current-task-state",
            "Candidate describes current task state.",
        );
    }
    if looks_like_one_off_write_scope(&lower, durable) {
        return reject(
            "one-off-write-scope",
            "Candidate describes a one-off task write scope.",
        );
    }
    if looks_like_rebuildable_code_fact(&lower, durable) {
        return reject(
            "rebuildable-code-fact",
            "Candidate can be rediscovered from the current repository.",
        );
    }
    if looks_like_ephemeral_reference(&lower, durable) {
        return reject(
            "ephemeral-reference",
            "Candidate is likely to expire quickly.",
        );
    }
    if looks_like_reference_pointer(&lower) {
        return MemoryGateDecision {
            disposition: MemoryGateDisposition::ReviewOnly,
            route: "review_only",
            flags: vec!["reference-pointer"],
            reason: "Reference-like memories should be reviewed without default compilation.",
        };
    }
    MemoryGateDecision {
        disposition: MemoryGateDisposition::Accept,
        route: "always_on_rule",
        flags: Vec::new(),
        reason: "Candidate passed memory gate.",
    }
}

fn reject(flag: &'static str, reason: &'static str) -> MemoryGateDecision {
    MemoryGateDecision {
        disposition: MemoryGateDisposition::Reject,
        route: "review_only",
        flags: vec![flag],
        reason,
    }
}

fn has_durable_marker(lower: &str) -> bool {
    [
        "以后",
        "长期",
        "每次",
        "所有",
        "默认",
        "统一",
        "总是",
        "必须",
        "合规",
        "团队",
        "always",
        "by default",
        "for every",
        "for all",
        "must",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn contains_secret(lower: &str) -> bool {
    [
        "token=",
        "password=",
        "passwd=",
        "credential",
        "api_key",
        "apikey",
        "secret=",
        "密钥",
        "密码",
        "凭证",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_generated_or_internal_artifact(lower: &str) -> bool {
    [
        "generated by agent-kernel",
        "do not edit directly",
        "enabled skilllets",
        "enabled skills",
        "contents of the agents.md",
        "contents of the claude.md",
        "observation synthesis",
        "source_observations",
        "matched_signal",
        "evidence:",
        "score:",
        "title:",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_current_task_state(lower: &str) -> bool {
    [
        "当前 pr",
        "current pr",
        "这个 pr",
        "本周 pr",
        "当前分支",
        "current branch",
        "正在改",
        "正在处理",
        "还有两项",
        "还有 2 项",
        "还有两个",
        "这次任务",
        "当前任务",
        "task status",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_one_off_write_scope(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    [
        "只修改",
        "仅修改",
        "只改 ",
        "不要改 rust",
        "不要动 rust",
        "不要改 src-tauri",
        "不要改前端",
        "不要改后端",
        "只读审查",
        "不要编辑文件",
        "不要修改文件",
        "modify only",
        "edit only",
        "do not touch rust",
        "do not modify",
        "read-only review",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_rebuildable_code_fact(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    let path_like = [
        ".rs",
        ".ts",
        ".tsx",
        ".js",
        ".py",
        "src/",
        "app/",
        "src-tauri/",
    ]
    .iter()
    .any(|marker| lower.contains(marker));
    path_like
        && [
            "这个函数",
            "函数现在在",
            "现在在",
            "located in",
            "lives in",
            "文件结构",
            "目录布局",
            "function signature",
        ]
        .iter()
        .any(|marker| lower.contains(marker))
}

fn looks_like_ephemeral_reference(lower: &str, durable: bool) -> bool {
    if durable {
        return false;
    }
    [
        "pr #",
        "pull request #",
        "分支名",
        "branch name",
        "今天改了",
        "本周任务",
        "本周列表",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn looks_like_reference_pointer(lower: &str) -> bool {
    lower.contains("http://")
        || lower.contains("https://")
        || lower.contains("看板")
        || lower.contains("dashboard")
        || lower.contains("监控")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decision(text: &str) -> MemoryGateDecision {
        evaluate_memory_candidate(text, text, text, "constraint", "project")
    }

    #[test]
    fn rejects_one_off_scope_without_durable_marker() {
        assert_eq!(
            decision("只修改 app/src/main.tsx，不要改 Rust。").disposition,
            MemoryGateDisposition::Reject
        );
        assert_eq!(
            decision("不要改 Rust。").disposition,
            MemoryGateDisposition::Reject
        );
    }

    #[test]
    fn keeps_durable_project_rule() {
        assert_eq!(
            decision("以后所有 Rust 项目提交前运行 cargo test。").disposition,
            MemoryGateDisposition::Accept
        );
    }
}
